FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
ENV QUIET_LOCALE=1
# ARG must be declared before use; placing after COPY so npm ci layer stays cached
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_WIDGET_URL
ARG EMBED_ALLOWLIST
ARG EMBED_ALLOWLIST_MODE=dynamic
ARG NEXT_PUBLIC_SENTRY_DSN
ARG NEXT_PUBLIC_WIDGET_VERSION=1
ARG NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE=0.1
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_WIDGET_URL=$NEXT_PUBLIC_WIDGET_URL
ENV EMBED_ALLOWLIST=$EMBED_ALLOWLIST
ENV EMBED_ALLOWLIST_MODE=$EMBED_ALLOWLIST_MODE
ENV NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN
ENV NEXT_PUBLIC_WIDGET_VERSION=$NEXT_PUBLIC_WIDGET_VERSION
ENV NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE=$NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE
# build:release = build:embed (minified loader + SRI manifest) + next build + build:sri.
# It deliberately omits check-locales (needs python3, absent from node:alpine) and
# tests. This ensures the deployed image generates the SRI manifest. (#8, #16)
RUN EMBED_ALLOWLIST="${EMBED_ALLOWLIST:-}" EMBED_ALLOWLIST_MODE="${EMBED_ALLOWLIST_MODE:-dynamic}" npm run build:release

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ARG EMBED_ALLOWLIST
ARG EMBED_ALLOWLIST_MODE=dynamic
ENV EMBED_ALLOWLIST=$EMBED_ALLOWLIST
ENV EMBED_ALLOWLIST_MODE=$EMBED_ALLOWLIST_MODE
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3001
ENV PORT=3001
ENV HOSTNAME=0.0.0.0
CMD ["node", "server.js"]
