export const minimalProps = {
  isEmbedded: true,
  isCollapsed: false,
  toggleCollapsed: () => {},
  messages: [],
  isTyping: false,
  input: '',
  setInput: () => {},
  handleSubmit: (e: any) => e.preventDefault(),
  flowResponses: [],
  widgetConfig: {},
  getLocalizedText: (t: any) => (typeof t === 'string' ? t : (t?.en || '')),
};

export const defaultStyles = {
  primaryColor: '#000',
  secondaryColor: '#000',
  backgroundColor: '#fff',
  textColor: '#000',
  borderRadius: 0,
  fontStyles: {},
  getShadowStyle: () => '',
  getButtonSizeClasses: () => ({ width: 'w-8', height: 'h-8', icon: 'w-4 h-4' }),
  widgetWidth: 300,
  widgetHeight: 500,
  messageBubbleRadius: 0,
  buttonBorderRadius: 0,
  backgroundOpacity: 1,
  showTimestamps: false,
  showTypingIndicator: false,
  showMessageAvatars: true,
  showUnreadBadge: false,
  spacingValues: { padding: '12px', gap: '10px' },
  openAnimation: 'slide',
  bubbleAnimation: 'none',
  messageAnimation: 'fade',
  respectReducedMotion: true,
  visualEffectStyles: {
    backdropFilter: undefined,
    WebkitBackdropFilter: undefined,
    backgroundOpacityOverride: undefined,
  },
};

export const baseWidgetConfig = {
  primary_color: '#000',
  background_color: '#fff',
  text_color: '#000',
  border_radius: 0,
  font_family: 'Inter',
  font_size: 14,
  font_weight: 'normal',
  shadow_intensity: 'md',
  shadow_color: '#000',
  size: 'sm',
  button_size: 'md',
  message_bubble_radius: 0,
  button_border_radius: 0,
  opacity: 1,
};
